name: nomad-events-demo
networks:
  nomad-events-demo:
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - nomad-events-demo
  nomad:
    image: hashicorp/nomad:1.6
    ports:
      - "4646:4646"
    command: agent -bind 0.0.0.0 -dev -data-dir /tmp/nomad
    networks:
      - nomad-events-demo
    privileged: true
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - nomad-events-demo
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml